In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
df = pd.read_csv('tourism.csv')
df

FileNotFoundError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: ignored

In [ ]:
df = pd.concat([df,pd.get_dummies(df['AttractionType'])],axis=1)

In [ ]:
df

AttractionType  AttractionsNearby  RestaurantsNearby  KidFriendlyscore  \
0      Historical          27.666667         338.333333                 6   
1         Worship          43.833333         227.666667                 4   
2      Historical          48.666667         344.666667                 6   
3         Worship          46.666667         548.000000                 4   
4      Historical          46.666667         462.666667                 7   
5      Historical          49.166667         476.666667                 7   
6      Historical          39.000000         306.000000                 6   
7      Historical          38.666667         465.000000                 7   
8        Shopping          39.500000         472.000000                 8   
9       Adventure          41.500000         468.666667                 7   
10        Worship           9.600000          19.000000                 4   
11     Historical         479.800000          26.600000                 6   
12     Historical         337.600000          22.700000                 7   
13      Amusement          72.333333           7.333333                 8   
14     Historical         828.333333          38.333333                 5   
15      Amusement         774.333333         774.333333                 7   
16       Shopping         635.666667         635.666667                 8   
17     Historical         601.333333         601.333333                 8   
18       Shopping         806.666667         806.666667                 8   
19     Historical         828.000000         828.000000                 7   
20     Historical          23.333333          28.666667                 5   
21      Adventure          10.833333          16.666667                 8   
22      Adventure          17.333333          17.000000                 8   
23      Adventure          22.500000          28.666667                 8   
24     Historical          23.833333          28.666667                 7   
25     Historical          35.166667         491.333333                 6   
26        Worship          32.166667         618.333333                 4   
27     Historical          35.000000         474.333333                 7   
28     Historical          35.166667         490.333333                 7   
29     Historical          30.500000         164.333333                 7   
30        Worship          42.833333         897.333333                 4   
31      Amusement          42.333333        1160.000000                 9   
32      Amusement           1.166667           4.333333                10   
33       Shopping          43.333333        1100.333333                 4   
34      Amusement          43.000000         938.333333                 9   
35      Adventure          34.500000         773.666667                 9   
36     Historical          43.333333        1000.000000                 8   
37       Shopping          43.500000        1151.666667                 7   
38       Shopping          43.166667        1001.333333                 6   
39        Worship          41.500000         823.333333                 5   
40        Worship          58.500000         763.333333                 5   
41      Amusement           8.333333          59.666667                10   
42      Adventure          53.000000         585.333333                 9   
43      Adventure          46.500000         265.666667                 9   
44        Worship          54.166667         510.000000                 4   
45       Shopping          58.166667         792.333333                 8   
46        Worship           8.333333          61.000000                 6   
47     Historical          55.666667         621.333333                 7   
48        Worship          54.500000         618.666667                 4   
49      Amusement           8.166667          58.333333                 9   
50     Historical          31.500000         420.333333                 8   

In [ ]:
df.drop(['AttractionType'],axis=1,inplace=True)
df

# "AttractionsNearby":20	"RestaurantsNearby":5	"Adventure":1	"Amusement":0	"Historical":0	"Shopping":0	"Worship":0


AttractionsNearby  RestaurantsNearby  KidFriendlyscore  LowMobilityscore  \
0           27.666667         338.333333                 6                 3   
1           43.833333         227.666667                 4                 6   
2           48.666667         344.666667                 6                 4   
3           46.666667         548.000000                 4                 5   
4           46.666667         462.666667                 7                 7   
5           49.166667         476.666667                 7                 5   
6           39.000000         306.000000                 6                 5   
7           38.666667         465.000000                 7                 6   
8           39.500000         472.000000                 8                 4   
9           41.500000         468.666667                 7                 3   
10           9.600000          19.000000                 4                 7   
11         479.800000          26.600000                 6                 4   
12         337.600000          22.700000                 7                 3   
13          72.333333           7.333333                 8                 2   
14         828.333333          38.333333                 5                 5   
15         774.333333         774.333333                 7                 6   
16         635.666667         635.666667                 8                 5   
17         601.333333         601.333333                 8                 5   
18         806.666667         806.666667                 8                 5   
19         828.000000         828.000000                 7                 4   
20          23.333333          28.666667                 5                 4   
21          10.833333          16.666667                 8                 2   
22          17.333333          17.000000                 8                 2   
23          22.500000          28.666667                 8                 2   
24          23.833333          28.666667                 7                 5   
25          35.166667         491.333333                 6                 5   
26          32.166667         618.333333                 4                 5   
27          35.000000         474.333333                 7                 6   
28          35.166667         490.333333                 7                 5   
29          30.500000         164.333333                 7                 4   
30          42.833333         897.333333                 4                 3   
31          42.333333        1160.000000                 9                 5   
32           1.166667           4.333333                10                 3   
33          43.333333        1100.333333                 4                 7   
34          43.000000         938.333333                 9                 4   
35          34.500000         773.666667                 9                 4   
36          43.333333        1000.000000                 8                 9   
37          43.500000        1151.666667                 7                 5   
38          43.166667        1001.333333                 6                 5   
39          41.500000         823.333333                 5                 5   
40          58.500000         763.333333                 5                 6   
41           8.333333          59.666667                10                 7   
42          53.000000         585.333333                 9                 5   
43          46.500000         265.666667                 9                 4   
44          54.166667         510.000000                 4                 8   
45          58.166667         792.333333                 8                 5   
46           8.333333          61.000000                 6                 8   
47          55.666667         621.333333                 7                 5   
48          54.500000         618.666667                 4                 6   
49  

In [ ]:

X = df.drop(['KidFriendlyscore','LowMobilityscore','SeniorCitizenscore'],axis=1).values
X

array([[2.76666667e+01, 3.38333333e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.38333333e+01, 2.27666667e+02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.86666667e+01, 3.44666667e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.66666667e+01, 5.48000000e+02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [4.66666667e+01, 4.62666667e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.91666667e+01, 4.76666667e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.90000000e+01, 3.06000000e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.86666667e+01, 4.65000000e+02, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0

In [ ]:
y = df[['KidFriendlyscore','LowMobilityscore','SeniorCitizenscore']].values
y

array([[ 6,  3,  4],
       [ 4,  6,  8],
       [ 6,  4,  5],
       [ 4,  5,  8],
       [ 7,  7,  7],
       [ 7,  5,  6],
       [ 6,  5,  7],
       [ 7,  6,  7],
       [ 8,  4,  5],
       [ 7,  3,  4],
       [ 4,  7,  9],
       [ 6,  4,  5],
       [ 7,  3,  6],
       [ 8,  2,  4],
       [ 5,  5,  6],
       [ 7,  6,  8],
       [ 8,  5,  6],
       [ 8,  5,  5],
       [ 8,  5,  6],
       [ 7,  4,  8],
       [ 5,  4,  6],
       [ 8,  2,  3],
       [ 8,  2,  3],
       [ 8,  2,  3],
       [ 7,  5,  6],
       [ 6,  5,  5],
       [ 4,  5,  8],
       [ 7,  6,  6],
       [ 7,  5,  4],
       [ 7,  4,  5],
       [ 4,  3,  7],
       [ 9,  5,  6],
       [10,  3,  2],
       [ 4,  7,  5],
       [ 9,  4,  7],
       [ 9,  4,  3],
       [ 8,  9,  9],
       [ 7,  5,  3],
       [ 6,  5,  4],
       [ 5,  5,  9],
       [ 5,  6,  9],
       [10,  7,  2],
       [ 9,  5,  5],
       [ 9,  4,  4],
       [ 4,  8,  8],
       [ 8,  5,  4],
       [ 6,  8,  9],
       [ 7,  

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=32)
X_train, X_test, y_train, y_test

(array([[3.95000000e+01, 4.72000000e+02, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [4.86666667e+01, 3.44666667e+02, 0.00000000e+00, 0.00000000e+00,
         1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [8.16666667e+00, 5.83333333e+01, 0.00000000e+00, 1.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.41666667e+01, 5.10000000e+02, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [4.31666667e+01, 1.00133333e+03, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
        [8.33333333e+00, 5.96666667e+01, 0.00000000e+00, 1.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [4.15000000e+01, 8.23333333e+02, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
        [6.35666667e+02, 6.35666667e+02, 0.00000000e+00, 0.00000000e+00,
         0

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [ ]:
print(model.predict([[4.23, 1.16, 0, 1,0, 0, 0]]))
print((np.round(model.predict([[4.23, 1.16, 0, 1,0, 0, 0]]))).astype(int))

[[8.970805   4.08095747 3.7438761 ]]
[[9 4 4]]


In [ ]:
from sklearn.metrics import classification_report
y_pred = (np.round(model.predict(X_test))).astype(int)
for i in range(len(y_test)):
  print(y_test[i], y_pred[i])

[8 5 4] [7 5 4]
[7 3 6] [7 5 6]
[6 9 9] [7 5 6]
[7 4 3] [7 5 4]
[8 2 3] [8 3 3]
[8 8 8] [5 6 8]
[6 5 5] [7 4 4]
[7 3 3] [7 5 4]
[7 5 4] [7 5 6]
[8 2 3] [8 3 3]
[7 6 6] [7 5 6]
[9 5 6] [9 6 6]


In [ ]:
from numpy import absolute, mean, std
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
n_scores = cross_val_score(model, X_test, y_test, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
n_scores = absolute(n_scores)
print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

MAE: 2.690 (4.046)


In [ ]:
import joblib
filename = "Tourism_model.joblib"
joblib.dump(model, filename)

['Tourism_model.joblib']